name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 当推送标签时触发，如 v1.0.0
  workflow_dispatch:  # 允许手动触发

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build executable
      run: |
        pyinstaller build.spec
        
    - name: Create release archive
      run: |
        cd dist
        7z a -tzip SwaggerAPITester-windows.zip SwaggerAPITester/
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: SwaggerAPITester-windows
        path: dist/SwaggerAPITester-windows.zip
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/SwaggerAPITester-windows.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pyqt5 python3-pyqt5.qtwebengine
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build executable
      run: |
        pyinstaller build.spec
        
    - name: Create release archive
      run: |
        cd dist
        tar -czf SwaggerAPITester-linux.tar.gz SwaggerAPITester/
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: SwaggerAPITester-linux
        path: dist/SwaggerAPITester-linux.tar.gz
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/SwaggerAPITester-linux.tar.gz
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}