name: Test Build

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

env:
  PYTHONIOENCODING: utf-8
  PYTHONLEGACYWINDOWSSTDIO: utf-8

jobs:
  test-build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller pillow
        
    - name: Create icon
      run: |
        python create_icon.py
      env:
        PYTHONIOENCODING: utf-8
        
    - name: Test build
      run: |
        pyinstaller build.spec --clean
        
    - name: Test executable
      run: |
        echo "Build completed successfully"
        dir dist/SwaggerAPITester/
        
    - name: Upload test artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-build-windows
        path: dist/SwaggerAPITester/
        retention-days: 7